package com.mt.crypto;

import java.security.GeneralSecurityException;
import java.security.KeyPair;

/**
 *
 * @author mkrajcovic
 *
 */
public interface AsymetricKeyGenerator {

	/**
	 *
	 * @return KeyPair instance holding public and private key generated by this method
	 * @throws Exception
	 */
	public KeyPair generateAsymetricKeyPair() throws GeneralSecurityException;

	/**
	 *
	 * @param keyPair
	 *            which to extract public key from
	 * @return public key as string
	 * @throws GeneralSecurityException
	 */
	public String getPublicKey(KeyPair keyPair) throws GeneralSecurityException;

	/**
	 *
	 * @param keyPair
	 *            which to extract private key from
	 * @return private key as string
	 * @throws Exception
	 */
	public String getPrivateKey(KeyPair keyPair) throws GeneralSecurityException;

}
