package com.mt.crypto;

import java.security.GeneralSecurityException;
import java.security.InvalidKeyException;
import java.security.KeyPair;

/**
 *
 * @author mkrajcovic
 */
public interface AsymetricKeyGenerator {

	/**
	 *
	 * @return KeyPair instance holding public and private key generated by this method
	 * @throws GeneralSecurityException
	 */
	public KeyPair generateAsymetricKeyPair() throws GeneralSecurityException;

	/**
	 *
	 * @param keyPair
	 *            which to extract public key from
	 * @return public key
	 * @throws GeneralSecurityException
	 */
	public String getPublicKey(KeyPair keyPair) throws InvalidKeyException;

	/**
	 *
	 * @param keyPair
	 *            which to extract private key from
	 * @return private key
	 * @throws GeneralSecurityException
	 */
	public String getPrivateKey(KeyPair keyPair) throws InvalidKeyException;

}
